### ISSUE TITLE
fastrangesize/fastrange64 fails to randomly select elements from half of range

### ISSUE THREAD

**Issue by dnbaker** [lemire/fastrange#1]
Hi!

This is very exciting work.

I was using fastrangesize to randomly select a minibatch of datapoints for a stochastic gradient descent algorithm, but I found that when the minibatch size was close to the number of possible samples, it would get stuck in an infinite loop.

Removed from that code in a simpler, reproducible test case:

```
#include "fastrange/fastrange.h"
#include <unordered_set>
#include <iostream>

int main(void) {
    std::unordered_set<int> set;
    const size_t max(400);
    size_t nsteps(0);
    while(set.size() < 256) {
        set.insert((((uint64_t)rand() << 32) | rand()) % max);
        ++nsteps;
    }
    std::cerr << "Number of steps: " << nsteps << '\n';
    set.clear();
    while(set.size() < 256) {
        set.insert(fastrangesize((((uint64_t)rand() << 32) | rand()), max));
        if(++nsteps % 1000 == 0)
            std::cerr << "Number of steps so far: " << nsteps
                           << ". Size of set: " << set.size() << '\n';
        
    }
    std::cerr << "Number of steps: " << nsteps << '\n';
}
```
My output is:

```
Number of steps: 408
Number of steps so far: 1000. Size of set: 191
Number of steps so far: 2000. Size of set: 200
Number of steps so far: 3000. Size of set: 200
Number of steps so far: 4000. Size of set: 200
Number of steps so far: 5000. Size of set: 200
Number of steps so far: 6000. Size of set: 200
Number of steps so far: 7000. Size of set: 200
Number of steps so far: 8000. Size of set: 200
Number of steps so far: 9000. Size of set: 200
Number of steps so far: 10000. Size of set: 200
Number of steps so far: 11000. Size of set: 200
Number of steps so far: 12000. Size of set: 200
Number of steps so far: 13000. Size of set: 200
Number of steps so far: 14000. Size of set: 200
Number of steps so far: 15000. Size of set: 200
Number of steps so far: 16000. Size of set: 200
Number of steps so far: 17000. Size of set: 200
Number of steps so far: 18000. Size of set: 200
Number of steps so far: 19000. Size of set: 200
<and so on for millions of steps>
```

When I add a short-circuit (as below)

```c++
#include "fastrange/fastrange.h"
#include <unordered_set>
#include <iostream>

int main(void) {
    std::unordered_set<int> set;
    const size_t max(400);
    size_t nsteps(0);
    while(set.size() < 256) {
        set.insert((((uint64_t)rand() << 32) | rand()) % max);
        ++nsteps;
    }
    std::cerr << "Number of steps: " << nsteps << '\n';
    set.clear();
    while(set.size() < 256) {
        set.insert(fastrangesize((((uint64_t)rand() << 32) | rand()), max));
        if(++nsteps % 1000 == 0)
            std::cerr << "Number of steps so far: " << nsteps
                      << ". Size of set: " << set.size() << '\n';
        if(nsteps > 1000000) break;
    }
    if(set.size() == 256) std::cerr << "Number of steps: " << nsteps << '\n';
    else {
        for(const auto el: set) std::cerr << "Element: " << el << '\n';
    }
}

```

When I check with Python `vals = set(int(line.split()[1]) for line in open("output.txt") if "Element" in line)`, the values in the set are precisely [0, 199].

I haven't tested with a 32-bit version, but it seems that something is off.

**Comment by lemire** [comment]
> it seems that something is off.

Yes. You are assuming that `` rand()`` generates 32 random bits, when it generates fewer than that (depending on your system). Try the following instead: 

```
#include "fastrange/fastrange.h"
#include <unordered_set>
#include <iostream>

/////////////////////
// rand returns a random integer between 0 and RAND_MAX
// where RAND_MAX is at least 32767
// Note: this means that (uint64_t)rand() << 32 | rand() is NOT a proper
// way to generate random 64-bit integers in general.
/////////////////////

static uint32_t get32rand() {
    return (((uint32_t)rand() << 0) & 0x0000FFFFul) |
           (((uint32_t)rand() << 16) & 0xFFFF0000ul);
}

static uint64_t get64rand() {
    return (((uint64_t)get32rand()) << 32) | get32rand();
}

int main(void) {
    std::unordered_set<int> set;
    srand(time(NULL));
    const size_t max(400);
    size_t nsteps(0);
    while(set.size() < 256) {
        set.insert((get64rand()) % max);
        ++nsteps;
    }
    std::cerr << "Number of steps: " << nsteps << '\n';
    set.clear();
    nsteps = 0;
    while(set.size() < 256) {
        set.insert(fastrangesize(get64rand(), max));
        ++nsteps;
    }
    std::cerr << "Number of steps: " << nsteps << '\n';
}
```

**Comment by dnbaker** [comment]
You're right. RAND_MAX, on the system I'm testing, is 2147483647, which is 31 bits of randomness, which precisely explains why I'm only getting half of what I expected.

Thank you!

**Comment by dnbaker** [comment]
Edit: I'm wrong. My apologies.

**Comment by aqrit** [comment]
if max_rand is 0x7FFF (as it is here)
then get32rand() is still wrong...
```
static uint32_t get32rand() {
    return (rand() ^ (rand() << 15) ^ (rand() << 30));
}
```
random side-rant:
the other day, I saw someone badly implement wrapping behavior w/fastrange for a hash table. [here](http://www.idryman.org/blog/2017/05/03/writing-a-damn-fast-hash-table-with-tiny-memory-footprints/)

IMO, fastrange with wrapping is pointless...
either add extra slots at the bottom of the table or use `abs((h & mask) - num_slots)` for wrapping

**Comment by lemire** [comment]
>  I saw someone badly implement wrapping behavior w/fastrange for a hash table

I did not know about this post. I have not read it carefully. Can you explain why it is wrong?

> if max_rand is 0x7FFF (as it is here) then get32rand() is still wrong...

I don't think so. Can you elaborate or prove me wrong?

**Comment by aqrit** [comment]
`index = ((key + probe * probe * 2) & mask) * rhh->capacity_ms4b >> 4;`
vs
`index = abs(((key + probe * probe) & mask) - rhh->capacity);`

if one is going to mask anyways then might as well avoid the multiplication. 
cmov might be slightly better than abs, but requires faith in the compiler.


>>if max_rand is 0x7FFF (as it is here) then get32rand() is still wrong...

>I don't think so. Can you elaborate or prove me wrong?

(0x7FFF << 16) | 0x7FFF == 0x7FFF7FFF

edit: should have said 
> (as it is for me)

**Comment by lemire** [comment]
>>I don't think so. Can you elaborate or prove me wrong?
>(0x7FFF << 16) | 0x7FFF == 0x7FFF7FFF

Sorry about this, you are correct, I was thinking about @dnbh's statement that set max_rand 
 to 2147483647.

**Comment by lemire** [comment]
@aqrit 

Conditional moves have gotten quite cheap so that something like an ``abs`` function can be used in high performance code without concern. Of course, what we must avoid are the divisions.

I had never given much thought to the idea of having hash tables that have capacities that are not a power of two. Or, at least, I don't think I gave it much thought recently. I somehow assumed that using a power of two was highly beneficial.

Now that I think about it, doing what you describe (``abs(x & mask -maxvalue)``) is only a handful of cycles. Well, it is still about five times more expensive than doing ``x & mask``, but it certainly is nothing like having to do a modulo reduction.

Interesting thought.

**Comment by dnbaker** [comment]
That sounds like the most obvious use case for a fast alternative to a modulo.

Another option for reducing hash table memory requirements was used in https://github.com/gmarcais/jellyfish, which uses a reversible hash function and uses the position in the table to represent some number of bits from the key. It still uses powers of two in size, but it's able to significantly reduce the space required for keys.

**Comment by lemire** [comment]
> That sounds like the most obvious use case for a fast alternative to a modulo.

Ah. The reason why I have not given this much thought is that using power-of-two capacities feel so attractive...

> Another option for reducing hash table memory requirements was used in https://github.com/gmarcais/jellyfish, which uses a reversible hash function and uses the position in the table to represent some number of bits from the key. It still uses powers of two in size, but it's able to significantly reduce the space required for keys.

I don't know jellyfish. 

Does it use chaining or probing?

**Comment by dnbaker** [comment]
Quadratic probing. [The deterministic probing lets them recover the "original" hash slot, building a lookup table and limiting reprobes to the size of the lookup table.] Its use case is specialized for counting "large" keys with most of these counts being one, so it stores 4 bits for each value at first and then adds an entry again and uses the concatenation of the value bits to store when they overflow. The use of duplicate entries per key, the lazy storage of the values, and the fact that one can only increment makes it not a general-purpose hash table, though I think it would be attractive to see a generic hash table which did so.

Instead of using their random binary matrices (which they refer to as an "almost universal" set of hash functions), as Thomas Wang's 64-bit hash is also reversible and fast to compute, if I were to implement such a table, I'd probably use it instead.
