### ISSUE TITLE
"-range % range" calculation is nonsensical

### ISSUE THREAD

**Issue by riking** [lemire/fastrange#3]
A number modulo itself is always zero; under a floating point calculation this always produces negative zero.

In the Go implementation:

```
thresh := uint32(-n) % uint32(n)
```

Again, this will always be zero, right?

**Comment by riking** [comment]
No, this is performing a two's complement negation operation and reinterpreting the sign bit.

**Comment by riking** [comment]
The expanded mathematical interpretation is:

```
threshold = ((~max) & MASK2_31 + 1 + POW2_31) % max;
```

where `~max` is the bitwise negation of `max` with infinite (or enough) bits to the left.

**Comment by lemire** [comment]
Thanks for the question. I see you found the answer. I will write a blog post on the issue at lemire.me.

**Comment by lemire** [comment]
See [What the heck is the value of “-n % n” in programming languages? ](https://lemire.me/blog/2020/10/28/what-the-heck-is-the-value-of-n-n-in-programming-languages/)
